In [6]:
#importing the pandas Libarary
import pandas as pd
import numpy as np

#Creating a Pandas Dataframe

In [9]:
#importing the boston house price data
from sklearn.datasets import load_diabetes
boston_dataset=load_diabetes()

In [10]:
type(boston_dataset)

sklearn.utils._bunch.Bunch

In [11]:
print(boston_dataset)

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]]), 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.]), 'frame': None, 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n', 'feature_names': ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], 'data_filename': 'diabetes_data_raw.csv.gz', 'target_filename': 'diabetes_target.csv.gz', 'data_module': 'sklearn.datasets.data'}

In [12]:
#pandas Dataframe
df=pd.DataFrame(boston_dataset.data,columns=boston_dataset.feature_names)

In [13]:
print(df)

          age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
..        ...       ...       ...       ...       ...       ...       ...
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

           s4        s5        s6
0   -0.002592  0.019907 -0.017646
1   -0.039493 -0.068332 -0.092204
2   -0.002592  0.002861 -0.025930
3    0.034309  0.022688 -0.009362
4   -0.002592 -0.031988 -0.046641
..        ...       ...       ...
437 -0.002592  0.031193  0.007207
438  0.034309 -0.018114  0.044485
439 -0.011080 -0.046883  0.015491
440  0.026560  0.044529 -0.025930
441 -0.039493 -0.004222  0.003064

[442 rows x 10 columns]

In [ ]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

importing the data fro CSV file to a pandas Datagram

In [ ]:
diebetes_df =pd.read_csv('/content/house_prices.csv')
type(diebetes_df)

pandas.core.frame.DataFrame

In [ ]:
diebetes_df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [ ]:
diebetes_df.shape

(62033, 21)

Exporting a Dataframe to a csv file

In [ ]:
df.to_csv('boston.csv')

In [ ]:
#creating a Dataframe with random values
random_df=pd.DataFrame(np.random.rand(20,10))

In [ ]:
random_df.head()

,0,1,2,3,4,5,6,7,8,9
0,0.932554,0.841724,0.788677,0.585728,0.259159,0.208315,0.953354,0.074655,0.363273,0.095293
1,0.719987,0.671266,0.365497,0.278313,0.647657,0.735975,0.581436,0.874022,0.350556,0.047695
2,0.865245,0.798802,0.771187,0.786734,0.239304,0.450494,0.821554,0.671807,0.057056,0.627728
3,0.218526,0.478347,0.922337,0.617110,0.400679,0.232746,0.859430,0.589144,0.558600,0.083749
4,0.899960,0.491542,0.136994,0.474739,0.116486,0.241663,0.325139,0.103584,0.568515,0.296604

In [ ]:
random_df.shape

(20, 10)

Inspecting a Dataframe

In [ ]:
#finding the number of rows & column
df.shape

(442, 10)

In [14]:
# first 5 rows in a Dataframe
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [ ]:
#last 5 rows of the Dataframe
df.tail()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [ ]:
#infomation about dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

In [ ]:
#number of missing values
df.isnull().sum()

age    0
sex    0
bmi    0
bp     0
s1     0
s2     0
s3     0
s4     0
s5     0
s6     0
dtype: int64

In [ ]:
df.value_counts('age')

age
 0.016281    19
 0.041708    17
 0.009016    16
-0.027310    15
-0.052738    14
 0.012648    14
-0.001882    14
 0.045341    14
 0.067136    13
 0.005383    13
 0.023546    12
 0.030811    12
 0.001751    12
-0.005515    12
 0.019913    11
 0.048974    11
-0.009147    11
-0.041840    11
 0.038076    10
-0.023677    10
 0.034443     9
-0.045472     9
 0.027178     9
-0.074533     8
 0.059871     7
-0.020045     7
-0.016412     7
-0.049105     7
 0.070769     7
-0.060003     7
-0.034575     6
 0.074401     6
-0.070900     6
-0.056370     6
 0.063504     6
-0.038207     6
-0.030942     5
-0.085430     5
 0.081666     5
 0.056239     5
-0.063635     4
-0.078165     4
-0.012780     4
-0.092695     4
-0.096328     4
 0.052606     4
-0.107226     3
-0.103593     3
-0.067268     3
-0.089063     3
-0.081798     2
-0.099961     2
 0.096197     2
 0.110727     2
 0.078034     1
 0.085299     1
 0.088931     1
 0.092564     1
Name: count, dtype: int64

In [ ]:
#group the values based on the mean
df.groupby('age').mean()

,sex,bmi,bp,s1,s2,s3,s4,s5,s6
age,,,,,,,,,
-0.107226,-0.044642,-0.041055,-0.044689,-0.034592,-0.034090,0.006915,-0.027193,-0.012052,-0.038357
-0.103593,0.018906,-0.035666,-0.025180,-0.036426,-0.024174,0.008142,-0.027193,-0.062093,-0.050783
-0.099961,-0.044642,-0.045546,-0.086577,-0.066239,-0.066449,0.013665,-0.039493,-0.033993,-0.030072
-0.096328,-0.044642,-0.066563,-0.044402,-0.051791,-0.040927,0.006301,-0.048719,-0.060841,-0.049747
-0.092695,-0.020811,-0.046085,-0.037517,-0.029432,-0.038187,0.034834,-0.048719,-0.022188,-0.029037
-0.089063,-0.044642,-0.038181,-0.027475,-0.036426,-0.034612,0.004460,-0.027193,-0.023367,-0.031453
-0.085430,0.012551,-0.015475,-0.018065,-0.035968,-0.024549,0.009615,-0.032113,-0.062239,-0.020960
-0.081798,0.003019,-0.019679,-0.029770,0.021134,0.019510,0.000779,0.034309,0.018144,-0.065280
-0.078165,-0.020811,-0.013212,-0.024606,-0.026680,-0.034038,0.023789,-0.039493,-0.009727,-0.059067
-0.074533,0.003019,-0.010787,-0.019011,-0.019284,-0.015014,-0.003363,-0.011818,-0.015599,-0.019717
-0.070900,-0.012868,-0.015727,-0.042779,-0.032987,-0.023391,-0.014561,-0.014401,-0.024400,-0.023859
-0.067268,-0.012868,-0.042133,-0.011409,-0.047434,-0.042336,-0.006584,-0.027193,-0.021875,-0.038357
-0.063635,0.003019,0.004842,0.010683,-0.025992,-0.016502,-0.012107,-0.011818,-0.010974,-0.023859
-0.060003,0.023445,0.015350,-0.015345,-0.023977,-0.020192,-0.000799,-0.015771,-0.013302,-0.031256
-0.056370,-0.012868,-0.023990,-0.033213,-0.026565,-0.023182,0.008142,-0.022519,-0.026129,-0.046641
-0.052738,-0.003789,0.001416,-0.014523,0.014254,0.010563,0.010509,0.001335,-0.006077,-0.007291
-0.049105,-0.017407,0.005650,-0.031408,-0.023191,-0.018269,-0.011844,0.000729,-0.002525,-0.009954
-0.045472,-0.002276,0.002656,-0.011409,0.019376,0.018241,0.001597,0.017047,0.004275,-0.000617
-0.041840,-0.009979,-0.005618,-0.013808,-0.005447,-0.000118,-0.004242,0.009317,-0.009203,-0.004090
-0.038207,-0.012868,0.014632,-0.040673,-0.002716,-0.003402,0.007528,-0.002469,0.001963,0.003755
-0.034575,0.018906,-0.028840,-0.004712,-0.012577,-0.006846,0.004460,-0.010895,-0.018165,0.019633
-0.030942,0.012551,0.028284,0.014298,-0.009549,-0.013214,-0.013948,0.010471,0.018030,-0.008533
-0.027310,-0.006513,0.003782,-0.009421,-0.001844,-0.003443,0.020660,-0.013023,-0.017268,0.000579
-0.023677,-0.025577,-0.000170,-0.009458,0.002284,0.002663,0.011456,-0.009972,-0.009947,-0.001492
-0.020045,-0.044642,0.002878,-0.004687,-0.011790,-0.013974,0.007616,-0.009603,-0.015785,0.001881
-0.016412,-0.017407,0.010269,0.036627,-0.007662,-0.011335,0.016031,-0.018407,-0.014641,-0.014096
-0.012780,-0.020811,-0.021026,-0.014854,0.001183,0.005419,-0.004744,-0.003699,-0.004014,-0.009362
-0.009147,0.007352,-0.002777,-0.021007,0.007062,0.015995,-0.017964,0.015858,0.007598,0.005324
-0.005515,0.003019,0.010859,-0.009113,-0.009137,-0.009404,-0.008425,-0.002008,0.011694,0.003064
-0.001882,-0.010598,-0.007361,0.014903,0.026540,0.021770,-0.001325,0.019548,0.014939,0.009869
0.001751,0.003019,-0.017254,-0.028241,-0.017507,-0.011543,-0.003516,-0.005975,-0.014910,-0.012468
0.005383,-0.000647,0.005070,0.013043,0.016107,0.021763,-0.004319,0.010295,0.003003,-0.005857
0.009016,-0.008896,0.003764,0.005159,0.021822,0.017808,0.010903,0.003981,0.009031,0.010572
0.012648,-0.003789,-0.003819,0.004410,0.015336,0.012722,0.005118,0.008373,0.011147,-0.005516
0.016281,-0.009523,-0.005525,0.000008,-0.017646,-0.017367,0.002717,-0.017761,-0.005474,0.010695
0.019913,-0.001314,0.001339,0.016552,0.000307,-0.001883,0.011154,-0.003397,0.000549,0.017750
0.023546,0.010963,0.008973,0.008772,-0.017622,-0.020651,-0.013334,0.003281,-0.003234,0.006171
0.027178,0.008315,0.026368,0.001980,0.012955,0.030001,-0.028265,0.026683,-0.006091,0.010428
0.030811,0.003019,0.016608,0.029140,0.005769,-0.000322,-0.004130,0.017334,0.018604,0.028953
0.034443,0.018906,0.021817,0.020342,-0.006461,-0.005559,-0.024175,0.017908,0.016479,0.003985
0.038076,0.050680,-0.003296,0.006149,-0.019869,-0.005761,-0.028674,0.013755,-0.002262,0.010520
0.041708,0.017037,-0.009059,0.010871,0.004825,0.001081,0.018321,-0.015030,-0.011967,-0.001809
0.045341,0.003019,0.015196,0.019332,0.029587,0.018705,0.008931,0.009875,0.026665,0.007502
0.048974,0.016018,0.036515,0.032095,0.009063,-0.001599,-0.002568,0.013711,0.032992,0.024905
0.052606,0.003019,-0.014828,0.000071,-0.010857,-0.030045,-0.013948,-0.008404,0.045376,-0.021788
0.056239,0.012551,-0.025175,0.007412,0.011915,0.015032,0.011824,-0.013367,-0.013813,0.008035
0.059871,0.023445,0.026898,0.024332,0.024378,0.028704,-0.026571,0.029037,0.030553,0.024958
0.063504,0.018906,0.004033,0.044251,0.053011,0.047433,0.000779,0.023608,0.032385,0.021704
0.067136,0.014018,-0.012922,0.004393,-0.013212,-0.016297,0.011257,-0.022121,-0.004907,0.013579
0.070769,0.009828,0.004726,0.032039,0.040299,0.030314,0.000779,0.024451,0.023615,0.023775
0.074401,-0.028755,0.044092,0.066056,0.046589,0.028487,0.007528,0.009708,0.046239,0.013420
0.078034,0.050680,-0.024529,-0.042406,0.006687,0.052861,-0.069172,0.080804,-0.037129,0.056912
0.081666,0.031616,0.002632,-0.006132,0.052093,0.055241,-0.016157,0.038442,0.026458,0.008035
0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
0.088931,-0.044642,0.006728,0.025315,0.030078,0.008707,0.063367,-0.039493,0.009434,0.032059
0.092564,-0.044642,0.036907,0.021872,-0.024960,-0.016658,0.000779,-0.039493,-0.022517,-0.021788
0.096197,-0.044642,0.046068,0.010976,0.050029,0.048633,-0.048923,0.088738,0.055600,0.042414
0.110727,0.050680,-0.013212,0.002937,-0.016016,0.006515,-0.054446,0.052759,0.008786,0.061054

statical Measures

In [ ]:
#count ot number of values
df.count()

age    442
sex    442
bmi    442
bp     442
s1     442
s2     442
s3     442
s4     442
s5     442
s6     442
dtype: int64

In [ ]:
#mean value-column wise
df.mean()

age   -1.444295e-18
sex    2.543215e-18
bmi   -2.255925e-16
bp    -4.854086e-17
s1    -1.428596e-17
s2     3.898811e-17
s3    -6.028360e-18
s4    -1.788100e-17
s5     9.243486e-17
s6     1.351770e-17
dtype: float64

In [ ]:
# stardard deviation -column wise
df.std()

age    0.047619
sex    0.047619
bmi    0.047619
bp     0.047619
s1     0.047619
s2     0.047619
s3     0.047619
s4     0.047619
s5     0.047619
s6     0.047619
dtype: float64

In [ ]:
df.min()

age   -0.107226
sex   -0.044642
bmi   -0.090275
bp    -0.112399
s1    -0.126781
s2    -0.115613
s3    -0.102307
s4    -0.076395
s5    -0.126097
s6    -0.137767
dtype: float64

In [ ]:
df.max()

age    0.110727
sex    0.050680
bmi    0.170555
bp     0.132044
s1     0.153914
s2     0.198788
s3     0.181179
s4     0.185234
s5     0.133597
s6     0.135612
dtype: float64

In [ ]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

Manupulating a Dataframe

In [16]:
# adding a column in aDataframe
df['outcome']=df.age
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,outcome
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,0.038076
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,-0.001882
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,0.085299
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,-0.089063
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,0.005383

In [18]:
#removing a row
df.drop(index=0,axis=0)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,outcome
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,-0.001882
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,0.085299
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,-0.089063
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,0.005383
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346,-0.092695
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,0.041708
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,-0.005515
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,0.041708
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,-0.045472
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,-0.045472

In [19]:
#removing a column
df.drop(columns='age',axis=1)

,sex,bmi,bp,s1,s2,s3,s4,s5,s6,outcome
0,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,0.038076
1,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,-0.001882
2,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,0.085299
3,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,-0.089063
4,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,0.005383
...,...,...,...,...,...,...,...,...,...,...
437,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,0.041708
438,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,-0.005515
439,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,0.041708
440,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,-0.045472
441,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,-0.045472

In [21]:
#locating a row using the index value
df.iloc[2]

age        0.085299
sex        0.050680
bmi        0.044451
bp        -0.005670
s1        -0.045599
s2        -0.034194
s3        -0.032356
s4        -0.002592
s5         0.002861
s6        -0.025930
outcome    0.085299
Name: 2, dtype: float64

In [22]:
#locating a column using the index value
df.iloc[:,2]

0      0.061696
1     -0.051474
2      0.044451
3     -0.011595
4     -0.036385
         ...
437    0.019662
438   -0.015906
439   -0.015906
440    0.039062
441   -0.073030
Name: bmi, Length: 442, dtype: float64

Correlation
positive correlation
nagative correlation

In [23]:
df.corr()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,outcome
age,1.000000,0.173737,0.185085,0.335428,0.260061,0.219243,-0.075181,0.203841,0.270774,0.301731,1.000000
sex,0.173737,1.000000,0.088161,0.241010,0.035277,0.142637,-0.379090,0.332115,0.149916,0.208133,0.173737
bmi,0.185085,0.088161,1.000000,0.395411,0.249777,0.261170,-0.366811,0.413807,0.446157,0.388680,0.185085
bp,0.335428,0.241010,0.395411,1.000000,0.242464,0.185548,-0.178762,0.257650,0.393480,0.390430,0.335428
s1,0.260061,0.035277,0.249777,0.242464,1.000000,0.896663,0.051519,0.542207,0.515503,0.325717,0.260061
s2,0.219243,0.142637,0.261170,0.185548,0.896663,1.000000,-0.196455,0.659817,0.318357,0.290600,0.219243
s3,-0.075181,-0.379090,-0.366811,-0.178762,0.051519,-0.196455,1.000000,-0.738493,-0.398577,-0.273697,-0.075181
s4,0.203841,0.332115,0.413807,0.257650,0.542207,0.659817,-0.738493,1.000000,0.617859,0.417212,0.203841
s5,0.270774,0.149916,0.446157,0.393480,0.515503,0.318357,-0.398577,0.617859,1.000000,0.464669,0.270774
s6,0.301731,0.208133,0.388680,0.390430,0.325717,0.290600,-0.273697,0.417212,0.464669,1.000000,0.301731
outcome,1.000000,0.173737,0.185085,0.335428,0.260061,0.219243,-0.075181,0.203841,0.270774,0.301731,1.000000